services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"  # Porta do PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data

    
  inventory-api:
    build:
      context: ./Inventory/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeia a porta do host para o container
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inventory_db
    depends_on:
      - db
  
  auth-api:
    build:
      context: ./Auth/
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Mapeia a porta do host para o container
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inventory_db

volumes:
  db_data:  # Volume persistente para o banco de dados