# kubernetes/sales-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deploy
  labels:
    app: sales-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      serviceAccountName: sales-sa 
      containers:
        - name: sales-api
          image: us-central1-docker.pkg.dev/key-hope-455618-p3/tcc-erp-repo/sales-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: KUBERNETES_DEPLOYMENT
              value: "true" 
            - name: GCP_PROJECT_ID
              value: "key-hope-455618-p3" 
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
        - name: cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.1
          command: ["/cloud-sql-proxy",
                    "key-hope-455618-p3:us-east1:auth-db-instance", # renomear para sales-db-instance
                    "--port=5432"]
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: gcp-sa-key
              mountPath: /var/run/secrets/tokens/gcp-sa-key
              readOnly: true
      volumes:
        - name: gcp-sa-key
          projected:
            sources:
              - serviceAccountToken:
                  audience: https://iam.googleapis.com/projects/key-hope-455618-p3/locations/global/workloadIdentityPools/gcp-service-account.iam.gserviceaccount.com
                  expirationSeconds: 3600
                  path: token