# kubernetes/customer-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP # Tipo ClusterIP para comunicação interna no cluster